### ISSUE TITLE
Doesn't build on OSX

### ISSUE THREAD

**Issue by pelson** [SciTools-incubator/iris-agg-regrid#13]
See comment at https://github.com/SciTools-incubator/iris-agg-regrid/pull/12#issuecomment-356815619

**Comment by bjlittle** [comment]
Closed by https://github.com/SciTools-incubator/iris-agg-regrid/pull/29

Also, see https://github.com/conda-forge/agg-regrid-feedstock/pull/1 and https://travis-ci.org/conda-forge/agg-regrid-feedstock/builds/336818371?utm_source=github_status&utm_medium=notification
