### ISSUE TITLE
Disable use of deprecated Numpy C API

### ISSUE THREAD

**Issue by pelson** [SciTools-incubator/iris-agg-regrid#14]
See comment https://github.com/SciTools-incubator/iris-agg-regrid/pull/12#issuecomment-356815760

**Comment by bjlittle** [comment]
@pelson Within the `setup.py` `setuptools.Extension`, using:
```python 
define_macros = [('NPY_NO_DEPRECATED_API', 'NPY_1_7_API_VERSION')]
```
causes the build to fail for other reasons.

Also, note that the [Cython documentation](http://docs.cython.org/en/latest/src/reference/compilation.html#configuring-the-c-build) suggests that you just *ignore* this warning.

I think that we can just live with this warning, not unless you know how to ignore it (and not turn off all warnings)

**Comment by pelson** [comment]
😢
